# Copyright 2018, The max Contributors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang
      env:
        - PROJECT_DIR="Projects/Clang\ X86\ Make"
      jobs:
        include:
          - stage: build
              script:
                - "cd ${TRAVIS_BUILD_DIR}/${PROJECT_DIR} && pwd && make"
                - "echo ${PROJECT_DIR}"
                - "echo ${TRAVIS_BUILD_DIR}"
          - stage: test
              script: "${PROJECT_DIR}/maxAutomatedTests"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang
      env:
        - PROJECT_DIR="Projects/Clang\ X86-64\ Make"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
      compiler: gcc
      env:
        - PROJECT_DIR="Projects/GCC\ X86\ Make"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
      compiler: gcc
      env:
        - PROJECT_DIR="Projects/GCC\ X86-64\ Make"
    #- os: osx
    #compiler: clang

#jobs:
  #include:
    #- stage: build
      #script:
        #- "cd ${TRAVIS_BUILD_DIR}/${PROJECT_DIR} && pwd && make"
        #- "echo ${PROJECT_DIR}"
        #- "echo ${TRAVIS_BUILD_DIR}"
    #- stage: test
      #script: "${PROJECT_DIR}/maxAutomatedTests"
