// Copyright 2015, Chris Blume
// All rights reserved.

#ifndef MAX_COMPILING_CONFIGURATION_PLATFORM_LINUX_HPP
#define MAX_COMPILING_CONFIGURATION_PLATFORM_LINUX_HPP

#define MAX_PLATFORM_LINUX

#endif // #ifndef MAX_COMPILING_CONFIGURATION_PLATFORM_LINUX_HPP