// Copyright 2015, Chris Blume
// All rights reserved.

#ifndef MAX_COMPILING_CONFIGURATION_PLATFORM_MACOS_HPP
#define MAX_COMPILING_CONFIGURATION_PLATFORM_MACOS_HPP

#define MAX_PLATFORM_MACOS

#endif // #ifndef MAX_COMPILING_CONFIGURATION_PLATFORM_MACOS_HPP