name: "Build and test"

on:
  push:
    branches: [ "tip-of-tree" ]
  pull_request:
    branches: [ "tip-of-tree" ]

permissions:
  contents: read

jobs:
  Windows:
    strategy:
      matrix:
        platform: [Win32, x64]
        configuration: [Debug, Release]
        runner: [windows-2022] # TODO: Add windows-2019, which errors on Platform Toolset = 'v143' missing.
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} .\Projects\VisualStudio

    - name: Test
      run: ${{ github.workspace }}\Projects\VisualStudio\maxAutomatedTests\${{ matrix.platform }}\${{ matrix.configuration }}\maxAutomatedTests.exe

  Linux:
    strategy:
      matrix:
        platform: [X86-64] # TODO: Add X86, AArch32, and AArch64 platforms
        #compiler: [clang-4, clang-5, clang-6, clang-7, clang-8, clang-9, clang-10, clang-11, clang-12, clang-13, clang-14, clang-15, clang-16, g++-7, g++-8, g++-9, g++-10, g++-11, g++-12]
        compiler: [g++-7, g++-8, g++-9, g++-10, g++-11, g++-12]
        runner: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Compiler
      run: |
           sudo apt update
           apt search ^g++$
           sudo apt install ${{ matrix.compiler }}
           set CXX ${{ matrix.compiler }}
           ${{ matrix.compiler }} --version

    - name: Build
      env:
        CXX: ${{ matrix.compiler }}
      working-directory: ${{ github.workspace }}/Projects/Make
      run: make

    - name: Test
      run: ${{ github.workspace }}/Projects/Make/maxAutomatedTests

    # TODO: Should this use perf stat record?
    # TODO: GitHub won't let us run perf stat on their machines. That is fine, really. We should host our own stable hardware.
    # Disable until we are hosting our own.
    #- name: Performance Test
    #  run: perf stat ${{ github.workspace }}/Projects/Make/maxAutomatedTests > perf_stats

    #- name: Upload performance test artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: perf_stats
